
export const THEMES = [
  {
    id: 'default',
    name: 'Default',
    background: '#e6e6e6',
    myMessageBubble: '#008080',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#d3d3d3',
    otherMessageText: '#333333',
    otherUsernameColor: '#008080',
    isLight: true
  },
  {
    id: 'one-dark-pro',
    name: 'One Dark Pro',
    background: '#282c34',
    myMessageBubble: '#61afef',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#3e4451',
    otherMessageText: '#abb2bf',
    otherUsernameColor: '#98c379',
    isLight: false
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    background: '#1a1b26',
    myMessageBubble: '#7aa2f7',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#24283b',
    otherMessageText: '#a9b1d6',
    otherUsernameColor: '#bb9af7',
    isLight: false
  },
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    background: '#1e1e2e',
    myMessageBubble: '#cba6f7',
    myMessageText: '#1e1e2e',
    myUsernameColor: '#1e1e2e',
    otherMessageBubble: '#313244',
    otherMessageText: '#cdd6f4',
    otherUsernameColor: '#f5c2e7',
    isLight: false
  },
  {
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    background: '#eff1f5',
    myMessageBubble: '#8839ef',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#e6e9ef',
    otherMessageText: '#4c4f69',
    otherUsernameColor: '#8839ef',
    isLight: true
  },
  {
    id: 'dracula',
    name: 'Dracula',
    background: '#282a36',
    myMessageBubble: '#bd93f9',
    myMessageText: '#282a36',
    myUsernameColor: '#282a36',
    otherMessageBubble: '#44475a',
    otherMessageText: '#f8f8f2',
    otherUsernameColor: '#50fa7b',
    isLight: false
  },
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    background: '#0d1117',
    myMessageBubble: '#238636',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#21262d',
    otherMessageText: '#c9d1d9',
    otherUsernameColor: '#58a6ff',
    isLight: false
  },
  {
    id: 'github-light',
    name: 'GitHub Light',
    background: '#ffffff',
    myMessageBubble: '#238636',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#f3f4f6',
    otherMessageText: '#1f2328',
    otherUsernameColor: '#0969da',
    isLight: true
  },
  {
    id: 'nord',
    name: 'Nord',
    background: '#2e3440',
    myMessageBubble: '#5e81ac',
    myMessageText: '#eceff4',
    myUsernameColor: '#eceff4',
    otherMessageBubble: '#3b4252',
    otherMessageText: '#d8dee9',
    otherUsernameColor: '#88c0d0',
    isLight: false
  },
  {
    id: 'pink',
    name: 'Pink',
    background: '#fce4ec',
    myMessageBubble: '#ec407a',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#f8bbd9',
    otherMessageText: '#880e4f',
    otherUsernameColor: '#c2185b',
    isLight: true
  },
  {
    id: 'magenta',
    name: 'Magenta',
    background: '#f3e5f5',
    myMessageBubble: '#8e24aa',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#e1bee7',
    otherMessageText: '#4a148c',
    otherUsernameColor: '#7b1fa2',
    isLight: true
  },
  {
    id: 'lime-green',
    name: 'Lime Green',
    background: '#e8f5e9',
    myMessageBubble: '#32cd32',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#c8e6c9',
    otherMessageText: '#1b5e20',
    otherUsernameColor: '#388e3c',
    isLight: true
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    background: '#fdf2f0',
    myMessageBubble: '#d7837f',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#f5d0ce',
    otherMessageText: '#6f4241',
    otherUsernameColor: '#b15e5b',
    isLight: true
  },
  {
    id: 'blush',
    name: 'Blush',
    background: '#fff0f3',
    myMessageBubble: '#ff758f',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#ffc2d1',
    otherMessageText: '#590d22',
    otherUsernameColor: '#ff4d6d',
    isLight: true
  },
  {
    id: 'cherry-blossom',
    name: 'Cherry Blossom',
    background: '#fff5f7',
    myMessageBubble: '#ff8fab',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#ffc8dd',
    otherMessageText: '#720026',
    otherUsernameColor: '#ff4d6d',
    isLight: true
  },
  {
    id: 'peach',
    name: 'Peach',
    background: '#fff3e0',
    myMessageBubble: '#ffab91',
    myMessageText: '#4e342e',
    myUsernameColor: '#4e342e',
    otherMessageBubble: '#ffe0b2',
    otherMessageText: '#5d4037',
    otherUsernameColor: '#ff8a65',
    isLight: true
  },
  {
    id: 'lavender',
    name: 'Lavender',
    background: '#f3e5f5',
    myMessageBubble: '#9c27b0',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#e1bee7',
    otherMessageText: '#4a148c',
    otherUsernameColor: '#7b1fa2',
    isLight: true
  },
  {
    id: 'sky-blue',
    name: 'Sky Blue',
    background: '#e0f7fa',
    myMessageBubble: '#4dd0e1',
    myMessageText: '#006064',
    myUsernameColor: '#006064',
    otherMessageBubble: '#b2ebf2',
    otherMessageText: '#00838f',
    otherUsernameColor: '#26c6da',
    isLight: true
  },
  {
    id: 'mint',
    name: 'Mint',
    background: '#e0f2f1',
    myMessageBubble: '#4db6ac',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#b2dfdb',
    otherMessageText: '#004d40',
    otherUsernameColor: '#00897b',
    isLight: true
  },
  {
    id: 'pastel-purple',
    name: 'Pastel Purple',
    background: '#ede7f6',
    myMessageBubble: '#7e57c2',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#d1c4e9',
    otherMessageText: '#311b92',
    otherUsernameColor: '#5e35b1',
    isLight: true
  },
  {
    id: 'sunset',
    name: 'Sunset',
    background: '#fff8e1',
    myMessageBubble: '#ff8a65',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#ffe0b2',
    otherMessageText: '#bf360c',
    otherUsernameColor: '#ff5722',
    isLight: true
  },
  {
    id: 'coral',
    name: 'Coral',
    background: '#fff3e0',
    myMessageBubble: '#ff7043',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#ffccbc',
    otherMessageText: '#bf360c',
    otherUsernameColor: '#f4511e',
    isLight: true
  },
  {
    id: 'amber',
    name: 'Amber',
    background: '#fff8e1',
    myMessageBubble: '#ffca28',
    myMessageText: '#3e2723',
    myUsernameColor: '#3e2723',
    otherMessageBubble: '#ffe082',
    otherMessageText: '#5d4037',
    otherUsernameColor: '#ffb300',
    isLight: true
  },
  {
    id: 'teal',
    name: 'Teal',
    background: '#e0f2f1',
    myMessageBubble: '#26a69a',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#b2dfdb',
    otherMessageText: '#004d40',
    otherUsernameColor: '#00897b',
    isLight: true
  },
  {
    id: 'purple-rain',
    name: 'Purple Rain',
    background: '#2d1b4e',
    myMessageBubble: '#a78bfa',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#4c3566',
    otherMessageText: '#ddd6fe',
    otherUsernameColor: '#c4b5fd',
    isLight: false
  },
  {
    id: 'midnight-pink',
    name: 'Midnight Pink',
    background: '#1a0f1f',
    myMessageBubble: '#f472b6',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#3d2644',
    otherMessageText: '#fbcfe8',
    otherUsernameColor: '#f9a8d4',
    isLight: false
  },
  {
    id: 'cotton-candy',
    name: 'Cotton Candy',
    background: '#f0f9ff',
    myMessageBubble: '#7dd3fc',
    myMessageText: '#0c4a6e',
    myUsernameColor: '#0c4a6e',
    otherMessageBubble: '#bae6fd',
    otherMessageText: '#0369a1',
    otherUsernameColor: '#38bdf8',
    isLight: true
  },
  {
    id: 'berry',
    name: 'Berry',
    background: '#fef3c7',
    myMessageBubble: '#f43f5e',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#fecdd3',
    otherMessageText: '#881337',
    otherUsernameColor: '#f43f5e',
    isLight: true
  },
  {
    id: 'olive',
    name: 'Olive',
    background: '#f9fbe7',
    myMessageBubble: '#aed581',
    myMessageText: '#33691e',
    myUsernameColor: '#33691e',
    otherMessageBubble: '#dcedc8',
    otherMessageText: '#558b2f',
    otherUsernameColor: '#8bc34a',
    isLight: true
  },
  {
    id: 'neon-pink',
    name: 'Neon Pink',
    background: '#1e1e2e',
    myMessageBubble: '#ff006e',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#45475a',
    otherMessageText: '#f5c2e7',
    otherUsernameColor: '#ff006e',
    isLight: false
  },
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    background: '#e0f7fa',
    myMessageBubble: '#00bcd4',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#b2ebf2',
    otherMessageText: '#00838f',
    otherUsernameColor: '#00acc1',
    isLight: true
  }
];