
export const THEMES = [
  {
    id: 'default',
    name: 'Default',
    background: '#e6e6e6',
    myMessageBubble: '#008080',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#d3d3d3',
    otherMessageText: '#333333',
    otherUsernameColor: '#008080',
    isLight: true,
    primary: '#008080'
  },
  {
    id: 'one-dark-pro',
    name: 'One Dark Pro',
    background: '#282c34',
    myMessageBubble: '#61afef',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#3e4451',
    otherMessageText: '#abb2bf',
    otherUsernameColor: '#98c379',
    isLight: false,
    primary: '#61afef'
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    background: '#1a1b26',
    myMessageBubble: '#7aa2f7',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#24283b',
    otherMessageText: '#a9b1d6',
    otherUsernameColor: '#bb9af7',
    isLight: false,
    primary: '#7aa2f7'
  },
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    background: '#1e1e2e',
    myMessageBubble: '#cba6f7',
    myMessageText: '#1e1e2e',
    myUsernameColor: '#1e1e2e',
    otherMessageBubble: '#313244',
    otherMessageText: '#cdd6f4',
    otherUsernameColor: '#f5c2e7',
    isLight: false,
    primary: '#cba6f7'
  },
  {
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    background: '#eff1f5',
    myMessageBubble: '#8839ef',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#e6e9ef',
    otherMessageText: '#4c4f69',
    otherUsernameColor: '#8839ef',
    isLight: true,
    primary: '#8839ef'
  },
  {
    id: 'dracula',
    name: 'Dracula',
    background: '#282a36',
    myMessageBubble: '#bd93f9',
    myMessageText: '#282a36',
    myUsernameColor: '#282a36',
    otherMessageBubble: '#44475a',
    otherMessageText: '#f8f8f2',
    otherUsernameColor: '#50fa7b',
    isLight: false,
    primary: '#bd93f9'
  },
  {
    id: 'nord',
    name: 'Nord',
    background: '#2e3440',
    myMessageBubble: '#5e81ac',
    myMessageText: '#eceff4',
    myUsernameColor: '#eceff4',
    otherMessageBubble: '#3b4252',
    otherMessageText: '#d8dee9',
    otherUsernameColor: '#88c0d0',
    isLight: false,
    primary: '#5e81ac'
  },
  {
    id: 'pink',
    name: 'Pink',
    background: '#fce4ec',
    myMessageBubble: '#ec407a',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#f8bbd9',
    otherMessageText: '#880e4f',
    otherUsernameColor: '#c2185b',
    isLight: true,
    primary: '#ec407a'
  },
  {
    id: 'magenta',
    name: 'Magenta',
    background: '#f3e5f5',
    myMessageBubble: '#8e24aa',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#e1bee7',
    otherMessageText: '#4a148c',
    otherUsernameColor: '#7b1fa2',
    isLight: true,
    primary: '#8e24aa'
  },
  {
    id: 'lime-green',
    name: 'Lime Green',
    background: '#e8f5e9',
    myMessageBubble: '#32cd32',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#c8e6c9',
    otherMessageText: '#1b5e20',
    otherUsernameColor: '#388e3c',
    isLight: true,
    primary: '#32cd32'
  },
  {
    id: 'blush',
    name: 'Blush',
    background: '#fff0f3',
    myMessageBubble: '#ff758f',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#ffc2d1',
    otherMessageText: '#590d22',
    otherUsernameColor: '#ff4d6d',
    isLight: true,
    primary: '#ff758f'
  },
  {
    id: 'cherry-blossom',
    name: 'Cherry Blossom',
    background: '#fff5f7',
    myMessageBubble: '#ff8fab',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#ffc8dd',
    otherMessageText: '#720026',
    otherUsernameColor: '#ff4d6d',
    isLight: true,
    primary: '#ff8fab'
  },
  {
    id: 'lavender',
    name: 'Lavender',
    background: '#f3e5f5',
    myMessageBubble: '#9c27b0',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#e1bee7',
    otherMessageText: '#4a148c',
    otherUsernameColor: '#7b1fa2',
    isLight: true,
    primary: '#9c27b0'
  },
  {
    id: 'sky-blue',
    name: 'Sky Blue',
    background: '#e0f7fa',
    myMessageBubble: '#4dd0e1',
    myMessageText: '#006064',
    myUsernameColor: '#006064',
    otherMessageBubble: '#b2ebf2',
    otherMessageText: '#00838f',
    otherUsernameColor: '#26c6da',
    isLight: true,
    primary: '#4dd0e1'
  },
  {
    id: 'mint',
    name: 'Mint',
    background: '#e0f2f1',
    myMessageBubble: '#4db6ac',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#b2dfdb',
    otherMessageText: '#004d40',
    otherUsernameColor: '#00897b',
    isLight: true,
    primary: '#4db6ac'
  },
  {
    id: 'pastel-purple',
    name: 'Pastel Purple',
    background: '#ede7f6',
    myMessageBubble: '#7e57c2',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#d1c4e9',
    otherMessageText: '#311b92',
    otherUsernameColor: '#5e35b1',
    isLight: true,
    primary: '#7e57c2'
  },
  {
    id: 'sunset',
    name: 'Sunset',
    background: '#fff8e1',
    myMessageBubble: '#ff8a65',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#ffe0b2',
    otherMessageText: '#bf360c',
    otherUsernameColor: '#ff5722',
    isLight: true,
    primary: '#ff8a65'
  },
  {
    id: 'coral',
    name: 'Coral',
    background: '#fff3e0',
    myMessageBubble: '#ff7043',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#ffccbc',
    otherMessageText: '#bf360c',
    otherUsernameColor: '#f4511e',
    isLight: true,
    primary: '#ff7043'
  },
  {
    id: 'amber',
    name: 'Amber',
    background: '#fff8e1',
    myMessageBubble: '#ffca28',
    myMessageText: '#3e2723',
    myUsernameColor: '#3e2723',
    otherMessageBubble: '#ffe082',
    otherMessageText: '#5d4037',
    otherUsernameColor: '#ffb300',
    isLight: true,
    primary: '#ffca28'
  },
  {
    id: 'teal',
    name: 'Teal',
    background: '#e0f2f1',
    myMessageBubble: '#26a69a',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#b2dfdb',
    otherMessageText: '#004d40',
    otherUsernameColor: '#00897b',
    isLight: true,
    primary: '#26a69a'
  },
  {
    id: 'purple-rain',
    name: 'Purple Rain',
    background: '#2d1b4e',
    myMessageBubble: '#a78bfa',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#4c3566',
    otherMessageText: '#ddd6fe',
    otherUsernameColor: '#c4b5fd',
    isLight: false,
    primary: '#a78bfa'
  },
  {
    id: 'midnight-pink',
    name: 'Midnight Pink',
    background: '#1a0f1f',
    myMessageBubble: '#f472b6',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#3d2644',
    otherMessageText: '#fbcfe8',
    otherUsernameColor: '#f9a8d4',
    isLight: false,
    primary: '#f472b6'
  },
  {
    id: 'cotton-candy',
    name: 'Cotton Candy',
    background: '#f0f9ff',
    myMessageBubble: '#7dd3fc',
    myMessageText: '#0c4a6e',
    myUsernameColor: '#0c4a6e',
    otherMessageBubble: '#bae6fd',
    otherMessageText: '#0369a1',
    otherUsernameColor: '#38bdf8',
    isLight: true,
    primary: '#7dd3fc'
  },
  {
    id: 'berry',
    name: 'Berry',
    background: '#fef3c7',
    myMessageBubble: '#f43f5e',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#fecdd3',
    otherMessageText: '#881337',
    otherUsernameColor: '#f43f5e',
    isLight: true,
    primary: '#f43f5e'
  },
  {
    id: 'olive',
    name: 'Olive',
    background: '#f9fbe7',
    myMessageBubble: '#aed581',
    myMessageText: '#33691e',
    myUsernameColor: '#33691e',
    otherMessageBubble: '#dcedc8',
    otherMessageText: '#558b2f',
    otherUsernameColor: '#8bc34a',
    isLight: true,
    primary: '#aed581'
  },
  {
    id: 'neon-pink',
    name: 'Neon Pink',
    background: '#1e1e2e',
    myMessageBubble: '#ff006e',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#45475a',
    otherMessageText: '#f5c2e7',
    otherUsernameColor: '#ff006e',
    isLight: false,
    primary: '#ff006e'
  },
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    background: '#e0f7fa',
    myMessageBubble: '#00bcd4',
    myMessageText: '#ffffff',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#b2ebf2',
    otherMessageText: '#00838f',
    otherUsernameColor: '#00acc1',
    isLight: true,
    primary: '#00bcd4'
  },
  {
    id: 'aurora',
    name: 'Aurora',
    background: '#071a1c',
    myMessageBubble: '#14b8a6',
    myMessageText: '#ecfeff',
    myUsernameColor: '#99f6e4',
    otherMessageBubble: '#12383a',
    otherMessageText: '#ccfbf1',
    otherUsernameColor: '#5eead4',
    isLight: false,
    primary: '#2dd4bf'
  },

  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    background: '#090014',
    myMessageBubble: '#ff00a8',
    myMessageText: '#ffffff',
    myUsernameColor: '#ff4dc4',
    otherMessageBubble: '#24103a',
    otherMessageText: '#f0abfc',
    otherUsernameColor: '#00f5ff',
    isLight: false,
    primary: '#00f5ff'
  },

  {
    id: 'amoled',
    name: 'AMOLED',
    background: '#000000',
    myMessageBubble: '#ffffff',
    myMessageText: '#000000',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#151515',
    otherMessageText: '#eeeeee',
    otherUsernameColor: '#aaaaaa',
    isLight: false,
    primary: '#ffffff'
  },

  {
    id: 'deep-ocean',
    name: 'Deep Ocean',
    background: '#061826',
    myMessageBubble: '#0284c7',
    myMessageText: '#ffffff',
    myUsernameColor: '#7dd3fc',
    otherMessageBubble: '#102f43',
    otherMessageText: '#dbeafe',
    otherUsernameColor: '#38bdf8',
    isLight: false,
    primary: '#0ea5e9'
  },

  {
    id: 'forest',
    name: 'Forest',
    background: '#0b1f17',
    myMessageBubble: '#16a34a',
    myMessageText: '#ffffff',
    myUsernameColor: '#86efac',
    otherMessageBubble: '#16382a',
    otherMessageText: '#dcfce7',
    otherUsernameColor: '#4ade80',
    isLight: false,
    primary: '#22c55e'
  },

  {
    id: 'coffee',
    name: 'Coffee',
    background: '#211914',
    myMessageBubble: '#a16207',
    myMessageText: '#fff7ed',
    myUsernameColor: '#fbbf24',
    otherMessageBubble: '#382820',
    otherMessageText: '#fed7aa',
    otherUsernameColor: '#d97706',
    isLight: false,
    primary: '#d97706'
  },

  {
    id: 'arctic',
    name: 'Arctic',
    background: '#f1f5f9',
    myMessageBubble: '#0284c7',
    myMessageText: '#ffffff',
    myUsernameColor: '#0369a1',
    otherMessageBubble: '#dbeafe',
    otherMessageText: '#1e3a5f',
    otherUsernameColor: '#0284c7',
    isLight: true,
    primary: '#0284c7'
  },

  {
    id: 'cosmic',
    name: 'Cosmic',
    background: '#100b25',
    myMessageBubble: '#8b5cf6',
    myMessageText: '#ffffff',
    myUsernameColor: '#c4b5fd',
    otherMessageBubble: '#25183f',
    otherMessageText: '#ede9fe',
    otherUsernameColor: '#a78bfa',
    isLight: false,
    primary: '#8b5cf6'
  },

  {
    id: 'matrix',
    name: 'Matrix',
    background: '#020a05',
    myMessageBubble: '#00ff41',
    myMessageText: '#001a07',
    myUsernameColor: '#00ff41',
    otherMessageBubble: '#092414',
    otherMessageText: '#86efac',
    otherUsernameColor: '#22c55e',
    isLight: false,
    primary: '#00ff41'
  },

  {
    id: 'noir',
    name: 'Noir',
    background: '#121212',
    myMessageBubble: '#f5f5f5',
    myMessageText: '#111111',
    myUsernameColor: '#ffffff',
    otherMessageBubble: '#292929',
    otherMessageText: '#d4d4d4',
    otherUsernameColor: '#a3a3a3',
    isLight: false,
    primary: '#f5f5f5'
  },

  {
    id: 'sakura-night',
    name: 'Sakura Night',
    background: '#1c1018',
    myMessageBubble: '#ec4899',
    myMessageText: '#ffffff',
    myUsernameColor: '#f9a8d4',
    otherMessageBubble: '#38202f',
    otherMessageText: '#fce7f3',
    otherUsernameColor: '#f472b6',
    isLight: false,
    primary: '#ec4899'
  },

  {
    id: 'desert',
    name: 'Desert',
    background: '#faf3e8',
    myMessageBubble: '#c2410c',
    myMessageText: '#ffffff',
    myUsernameColor: '#9a3412',
    otherMessageBubble: '#ead7bd',
    otherMessageText: '#4a2c1a',
    otherUsernameColor: '#c2410c',
    isLight: true,
    primary: '#c2410c'
  },

  {
    id: 'vaporwave',
    name: 'Vaporwave',
    background: '#170b2e',
    myMessageBubble: '#ff71ce',
    myMessageText: '#ffffff',
    myUsernameColor: '#ff71ce',
    otherMessageBubble: '#30205a',
    otherMessageText: '#c4b5fd',
    otherUsernameColor: '#01cdfe',
    isLight: false,
    primary: '#01cdfe'
  },

  {
    id: 'crystal',
    name: 'Crystal',
    background: '#eef2ff',
    myMessageBubble: '#6366f1',
    myMessageText: '#ffffff',
    myUsernameColor: '#4f46e5',
    otherMessageBubble: '#dbeafe',
    otherMessageText: '#1e293b',
    otherUsernameColor: '#6366f1',
    isLight: true,
    primary: '#6366f1'
  },

  {
    id: 'soft-minimal',
    name: 'Soft Minimal',
    background: '#f8fafc',
    myMessageBubble: '#334155',
    myMessageText: '#ffffff',
    myUsernameColor: '#475569',
    otherMessageBubble: '#e2e8f0',
    otherMessageText: '#334155',
    otherUsernameColor: '#64748b',
    isLight: true,
    primary: '#475569'
  },
  {
    id: 'royal',
    name: 'Royal',
    background: '#100c1c',
    myMessageBubble: '#7c3aed',
    myMessageText: '#ffffff',
    myUsernameColor: '#c4b5fd',
    otherMessageBubble: '#261947',
    otherMessageText: '#ede9fe',
    otherUsernameColor: '#a78bfa',
    isLight: false,
    primary: '#8b5cf6'
  },

  {
    id: 'chocolate',
    name: 'Chocolate',
    background: '#1c110d',
    myMessageBubble: '#92400e',
    myMessageText: '#fff7ed',
    myUsernameColor: '#fdba74',
    otherMessageBubble: '#352018',
    otherMessageText: '#fed7aa',
    otherUsernameColor: '#f59e0b',
    isLight: false,
    primary: '#d97706'
  }
];
