import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  // ── ActiveCallScreen
  screen: { flex: 1, backgroundColor: '#0a0a0f' },
  minimizeBtn: {
    position: 'absolute',
    top: 48,
    left: 20,
    zIndex: 30,
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.35)',
  },

  // ── CallControls
  bar: {
    height: 110,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 26,
    backgroundColor: 'rgba(10,10,15,0.92)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.06)',
  },
  btn: {
    width: 50,
    height: 50,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnActive: { backgroundColor: 'rgba(239,68,68,0.2)' },
  endBtn: {
    width: 64,
    height: 64,
    borderRadius: 999,
    backgroundColor: '#ef4444',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ── CallContent
  contentWrap: { flex: 1, backgroundColor: '#000', overflow: 'hidden' },
  centerColumn: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24 },
  centerFillDark: { ...StyleSheet.absoluteFillObject, alignItems: 'center', justifyContent: 'center', backgroundColor: '#111318' },
  glow: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: 'rgba(99,102,241,0.15)',
  },
  textWrap: { alignItems: 'center' },
  contentName: { color: '#fff', fontSize: 22, fontWeight: '600' },
  contentStatus: { color: 'rgba(255,255,255,0.5)', fontSize: 14, marginTop: 4 },
  localPreview: {
    position: 'absolute',
    bottom: 128,
    right: 16,
    width: 112,
    height: 168,
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.2)',
    zIndex: 20,
  },
  localPreviewMini: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    width: 44,
    height: 64,
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    zIndex: 20,
  },
  lostBadge: {
    position: 'absolute',
    top: 16,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(220,38,38,0.9)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    zIndex: 30,
  },
  lostText: { color: '#fff', fontSize: 11, fontWeight: '700', letterSpacing: 0.5, textTransform: 'uppercase' },

  // ── CallErrorScreen
  errorBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24 },
  errorCard: { width: '100%', maxWidth: 360, borderRadius: 24, borderWidth: 1, paddingVertical: 32, paddingHorizontal: 24, alignItems: 'center' },
  errorIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(239,68,68,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  errorTitle: { fontSize: 19, fontWeight: '700', marginBottom: 8 },
  errorMessage: { fontSize: 13, opacity: 0.7, textAlign: 'center', marginBottom: 26 },
  errorDismissBtn: { width: '100%', paddingVertical: 13, borderRadius: 14, backgroundColor: '#ef4444', alignItems: 'center' },
  errorDismissText: { color: '#fff', fontWeight: '600', fontSize: 14 },

  // ── IncomingCallScreen
  incomingBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.85)', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24 },
  incomingCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 28,
    backgroundColor: '#17151f',
    borderWidth: 1,
    borderColor: 'rgba(168,85,247,0.25)',
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 24,
    overflow: 'hidden',
  },
  incomingGlow: {
    position: 'absolute',
    top: -80,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: 'rgba(168,85,247,0.18)',
  },
  incomingName: { color: '#f5f3ff', fontSize: 22, fontWeight: '700' },
  incomingSub: { color: '#c4b5fd', fontSize: 13, fontWeight: '600', marginTop: 6, marginBottom: 36 },
  incomingActions: { flexDirection: 'row', gap: 40 },
  incomingActionCol: { alignItems: 'center', gap: 8 },
  declineBtn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e11d48',
  },
  acceptBtn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#16a34a',
  },
  incomingActionLabel: { color: '#c4b5fd', fontSize: 12, fontWeight: '600' },

  // ── MinimizedView
  miniWrap: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 150,
    height: 220,
    zIndex: 999,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#0a0a0f',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    elevation: 10,
    shadowColor: '#000',
    shadowOpacity: 0.4,
    shadowRadius: 10,
  },
  expandBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    zIndex: 30,
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  miniFooter: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    backgroundColor: '#111318',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.06)',
  },
  miniFooterText: { flex: 1, minWidth: 0, marginRight: 6 },
  miniName: { color: '#fff', fontSize: 12, fontWeight: '600' },
  miniStatus: { color: 'rgba(255,255,255,0.5)', fontSize: 10, marginTop: 1 },
  miniFooterActions: { flexDirection: 'row', gap: 6 },
  miniBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  miniBtnActive: { backgroundColor: 'rgba(239,68,68,0.2)' },
  miniEndBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ef4444',
  },
});
